sudo: required
dist: trusty
language: csharp
mono: none
dotnet: 1.0.0-preview2-003131
before-install:
- sudo apt-get -qq update
- sudo apt-get install -y libsnappy1 libsnappy-dev
script:
- dotnet restore
- dotnet test ./test/Snappy.Tests -c Release
